# ========================================
# Syphia Sistem Ayarları
# Cartel tarafından geliştirildi
# ========================================

Developer:
  Name: ''
  ID: ''
  TotalShards: auto

Secret: ''

Signature: ''

Presence:
  Status: 'idle'
  Message:
    - '✨ Syphia Music'
    - '🌙 /play'

EmojiSystem:
  TargetGuild: ''

Database:
  URL: 'mongo db url koyacaksınız'
